---
title: "Untitled"
author: "chikako watanabe"
date: "2020/5/14"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## はじめに

問題：個体は摂餌から得られるエネルギーをどう利用するか？

解決のため

1. 個体の成長と再生産を記述する
2. 極限サイズをmaster trait（支配的な特性？）として確立する
3. 個体のサイズ、極限サイズ、生活史パラメータのセットに関するエネルギー収支のパラメータを決定する


## 個体は摂餌から得られるエネルギーをどう利用するか？
- Size spectrum theoryをpopulationまで発展→個体について詳細な記述が必要
- 個体のサイズの関数としてエネルギー収支（enegy budget)を表現し、摂餌率（consumption rate)から成長率（growth rate）と再生産率（reproduction rate)を決定する

Enegy budget 個体の中での質量とエネルギーの流れ
Assmilation losses, Metabolic losses,
Enegy spent on growth and reproduction

## Master trait
- 魚類の多様な生態の表現には多くのパラメータが必要↔シンプルな理論構築には邪魔
- Life-history invariants を利用してパラメータを減らし、最終的に種によって変化するパラメータは一つに絞られた
- 極限サイズ（W∞）である。これは生活史の多様さを特徴づけるmaster trait の役割を果たすパラメータである。


Life History Invariants：生活史においてkeyになる無次元の
重要パラメータが異なる種間系統間で一定値をとるとき、
そのパラメータ

## 3.1 The von Bertallanffy growth model
本章では、成熟前と成熟後の異なる成長様式を一つのモデルで記述する(biphasic growth model)
- 成熟前：エネルギーをすべて成長に使う
- 成熟後：エネルギーを成長と再生産に使う

再生産にかかるコストを考慮した成長モデルがのちの章で必要になる。 
最初にもとになるvon Bertalanffyの成長式を詳しく見ていく


## von Bertalanffy growth model

同化作用(anabolic)と異化作用(catabolic)のプロセスから構成

$$
\frac{dw}{dt}= Aw^n-kw
$$

$Aw^n$ :エネルギーの獲得(accuisition, anabolic) 
$kw$  :エネルギーの損失(losses, catabolic)　

いずれも体重のべき乗に比例する（それぞれ,nと1）

## nについて

- エネルギーの獲得は同化作用の過程によって限定される
- それらは組織の表面積からの酸素や食料の吸収と解釈
- シンプルな2/3乗則に従うと考えた



## 式の導出

BOX 3.1 

数式（１）は$w=cl^3$の関係を使って以下の様にかける
$$
\frac{dl}{dt} = K(L_\infty-l)
$$
ここで$K= k/3$, $L_\infty=c^{-1/3}Ak$

これを解くと（例えば赤嶺****）von Bertalanffy の成長式になる
$$
l(t) = L_\infty(1-e^{-K_t})
$$
K：growth constany（時間あたり）, L∞：極限体長


## K,L∞と、A,k,c の関係

$$
\frac{dw}{dt}=\frac{dcl^3}{dt}=3cl^2\frac{dl}{dt}=Aw^n-kw
$$

とかける。$w=cl^3$を用いて変形すると


$$
\frac{dl}{dt} = \frac{1}{3cl^3}A(cl^3)^n-\frac{kcl^3}{3cl^3}
$$
ここでn=2/3 ならば
$$
\frac{dl}{dt}=\frac{1}{3}C^{-1/3}A-\frac{k}{3}l =\frac{k}{3}(\frac{c^{-1/3}A}{k}-l)
$$
となり、$K=\frac{k}{3}$,  $L_\infty = \frac{c^{-1/3}A}{k}$ となる

図3.1a　初期の成長は傾き$KL_\infty$の直線似近く（斜めの破線）、$l$が$L_\infty$に近づくと成長が止まる（横の破線）。

この成長式はシンプルで、年齢あたりのサイズの変化によく一致し、体長という測定しやすい変数を用いたという点で大いに成功した。

## von Bertallanfy 式の問題

- $K$と$L_\infty$に相関関係がある（負、図3.2）
	- $L_\infty$の誤差は$K$に影響し、往々にして$L_\infty$の不確実性は高い
	
	  （いっぽうが過大推定されると、もう一方は過小推定される）
	
	- Aを確かな筋から推定できれば、$L_\infty$の不確実性の$K$への影響は制限されるだろう
- nは3/4のほうがいい
	-　von Bertallanfy は、Haldanes(1928)を読むべきであった
	-　West(1997)は、代謝を表す体重のべき数に3/4乗則を採用した
	-　この本でも近年の代謝生態学の流れに基づき、代謝のべき数として3/4を採用する 

## 3.2 Master Traitとして極限サイズ

von Bertalanffy の成長式は、エネルギーの獲得と損失の重要性が年齢や体のサイズによって変化することで形が決まる。

図3.1b　体が大きくなるほどAw0.75は増えていくがkwも増えていき、両者が一致するところで成長が止まる。

年齢が重なり体が大きくなると、損失が大きくなって成長にエネルギーが回らなくなり、それ以上サイズは増えなくなる（極限サイズ）

このときの関係は以下のようにかける
$$
W_\infty=(\frac{A}{k})^\frac{1}{1-n}
$$

## Aの決定
AとkにはW∞の決定においてトレードオフの関係がある。

式3.4と上の式を使うと、種による成長の違いは、AとW∞だけで記述できる
$$
\frac{dw}{dt}=Aw^n[1-(\frac{w}{W_\infty})^{1-n}]
$$
(この式は体重の増加を示した成長式で、W∞とAだけで記述できる)

Aはエネルギーの獲得と同化のプロセスを表現する成長係数であり、このプロセスは種の極限体長とは関係しないと期待できる。

Aの値を決めるために、von Bertalanffy 成長式で推定された$K$ と$L_\infty$の値に頼るとしよう（図3.3）。

$KL_\infty$とAの関係は、$n=2/3$で確認されているのであるが、box3.2から、$n=3/4$でも概ねOK。

図3.3をみると、大雑把に見ればAは$W_\infty$に対して独立のようである。データは同じ極限サイズでも成長速度は2倍近くことなることも示す。実際にはAは極限サイズが大きくなるにつれて若干増加する。これは大型の種は小型の種より成長が速いことを示す。速い成長は高い体温、高い代謝を伴い、それはサバ科魚類に多い。そして実際、サバ科魚類は大型魚種の主要な種である。

以下では単純のため、Aは一定として扱う。A=5.35g^0.25/yr

## Biphasic Growth Equation

Von Bertalanffy の式から派生。主な違いは、すべてのエネルギーを成長に使う幼魚と、繁殖も行う成魚の様式を区別した上で統合し、成長式に再生産によるロスを反映できるようにした。

初回成熟時の体重（＝半数成熟体重）の極限体重に対する比率を$\eta_m$とする


未成魚の成長　$g_j(w) = Aw^n$

成魚の成長　　$g(w) = Aw^n-kw$ ,    $w>\eta_mW_\infty$

両者の間を成熟関数でつなぐ
$$
\psi_m(w/w_m) = [1+(\frac{w}{w_m})^{-u}]^{-1}=[1+(\frac{w}{\eta_mW_\infty})^{-u}]^{-1}
$$
$\psi(w/w_m)$は、$w<<w_m$ではゼロに、$w>>w_m$では1に近づく。uはその変化の強さを決めるペラメータ（図3.4bの立ち上がり＝steepnessを決める）

成熟関数を導入することにより、以下のように生活史の異なるphaseを一つの式でまとめることができる。
$$
g_{bp}(w)=Aw^n-\psi_m(w/w_m)kw
$$
ふたたび$k=AW_\infty^{n-1}$を用いて
$$
g_{bp}(w) = Aw^n[1-\psi(\frac{w}{\eta_mW_\infty})(\frac{w}{W_\infty})^{1-n}]
$$


## para2

## para3

## 3.3 成長式における生体エネルギー的定式化